---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: homelab-cluster
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/TopherMayor/homelab-cluster.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: homelab-cluster
  path: ./clusters/pi-cluster/apps
  prune: true
  wait: true
  timeout: 5m