---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-settings
  namespace: default
data:
  settings.yaml: |
    # Homepage configuration
    providers:
      openweathermap: openweathermapapikey
      weatherapi: weatherapiapikey