---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-settings
  namespace: default
data:
  settings.yaml: |
    # Homepage configuration
    providers:
      openweathermap: openweathermapapikey
      weatherapi: weatherapiapikey

    # Basic homepage settings
    title: Homelab Dashboard
    theme: dark

    # Services configuration
    services:
      - name: Management
        services:
          - name: Portainer
            icon: portainer.png
            href: https://portainer.k3s.tophermayor.com
          - name: Gitea
            icon: gitea.png
            href: https://gitea.k3s.tophermayor.com
          - name: Code Server
            icon: vscode.png
            href: https://code.k3s.tophermayor.com
          - name: Traefik Dashboard
            icon: traefik.png
            href: https://traefik.k3s.tophermayor.com
          - name: Uptime Kuma
            icon: uptime-kuma.png
            href: https://uptime.k3s.tophermayor.com
      - name: Home & Automation
        services:
          - name: Home Assistant
            icon: home-assistant.png
            href: https://homeassistant.k3s.tophermayor.com
          - name: AdGuard
            icon: adguard-home.png
            href: https://adguard.k3s.tophermayor.com
          - name: Mosquitto
            icon: mqtt.png
            href: http://mosquitto.default.svc.cluster.local:1883
      - name: Productivity
        services:
          - name: Nextcloud
            icon: nextcloud.png
            href: https://nextcloud.k3s.tophermayor.com
          - name: Vaultwarden
            icon: bitwarden.png
            href: https://vaultwarden.k3s.tophermayor.com

  docker.yaml: |
    # Docker integration disabled
    # This is optional and can be configured later

  services.yaml: |
    # Additional services configuration
    # This is optional and can be configured later
