apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
      - name: homepage
        image: ghcr.io/gethomepage/homepage:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: homepage-config
          mountPath: /app/config/settings.yaml
          subPath: settings.yaml
        - name: homepage-config
          mountPath: /app/config/docker.yaml
          subPath: docker.yaml
        - name: homepage-config
          mountPath: /app/config/services.yaml
          subPath: services.yaml
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: HOMEPAGE_ALLOWED_HOSTS
          value: "homepage.k3s.tophermayor.com,homepage.local,localhost"
      volumes:
      - name: homepage-config
        configMap:
          name: homepage-settings
---
apiVersion: v1
kind: Service
metadata:
  name: homepage
spec:
  selector:
    app: homepage
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homepage
  namespace: default
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`homepage.k3s.tophermayor.com`)
    kind: Rule
    services:
    - name: homepage
      port: 3000
  tls:
    secretName: wildcard-tophermayor-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homepage-http
  namespace: default
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`homepage.k3s.tophermayor.com`)
    kind: Rule
    middlewares:
    - name: https-redirect
      namespace: default
    services:
    - name: homepage
      port: 3000
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: default
spec:
  redirectScheme:
    scheme: https
    permanent: true