apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-settings
  namespace: default
  labels:
    kustomize.toolkit.fluxcd.io/name: apps
    kustomize.toolkit.fluxcd.io/namespace: flux-system
data:
  docker.yaml: |
    # Docker integration disabled
    # This is optional and can be configured later
  kubernetes.yaml: |
    # Kubernetes service discovery disabled
    # Services are manually configured in services.yaml
  services.yaml: |
    # Services disabled - configured in settings.yaml instead
  settings.yaml: |
    # Homepage configuration
    providers:
      openweathermap: openweathermapapikey
      weatherapi: weatherapiapikey

    # Basic homepage settings
    title: Homelab Dashboard
    theme: dark
    layout:
      style: row
      columns: 4
      background:
        image: /images/background.jpg
        opacity: 0.8

    # Services configuration
    services:
      - name: Management
        services:
          - name: Homepage
            icon: home.png
            description: Homelab Homepage
            href: https://homepage.k3s.tophermayor.com
            target: _blank
          - name: Traefik Dashboard
            icon: traefik.png
            description: Traefik Reverse Proxy Dashboard
            href: https://traefik.k3s.tophermayor.com/dashboard/
            target: _blank
          - name: Portainer
            icon: portainer.png
            description: Container Management Interface
            href: https://portainer.k3s.tophermayor.com
            target: _blank
      
      - name: Home & Automation
        services:
          - name: Home Assistant
            icon: home-assistant.png
            description: Home Automation Hub
            href: https://homeassistant.k3s.tophermayor.com
            target: _blank
          - name: AdGuard Home
            icon: adguard-home.png
            description: DNS-based Ad Blocker
            href: https://adguard.k3s.tophermayor.com
            target: _blank