apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- adguard.yaml
- adguard-pvc.yaml
- cert-manager.yaml
- cert-issuer.yaml
- homepage.yaml
- homepage-pvc.yaml
- homepage-configmap.yaml
- nfs-storageclass.yaml
