apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: system-config
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/pi-cluster/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-cluster
  targetNamespace: kube-system
resources:
  - coredns-config.yaml
commonLabels:
  app.kubernetes.io/part-of: homelab-cluster
  app.kubernetes.io/managed-by: flux
commonAnnotations:
  fluxcd.io/managed-by: "kustomize"