---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-nextcloud
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.254.12
  share: /mnt/TrueNAS/Homelab/NextCloud
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
mountOptions:
- nfsvers=4.1
- tcp
- hard
- timeo=600
- retrans=2