---
apiVersion: v1
kind: Service
metadata:
  name: homepage-nodeport
  namespace: default
spec:
  selector:
    app: homepage
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30090
    name: web