apiVersion: batch/v1
kind: Job
metadata:
  name: uptime-kuma-setup
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: setup
        image: curlimages/curl:latest
        command:
        - /bin/bash
        - /scripts/setup.sh
        volumeMounts:
        - name: setup-script
          mountPath: /scripts
      volumes:
      - name: setup-script
        configMap:
          name: uptime-kuma-setup
          defaultMode: 0755